# Generated by Django 3.0.4 on 2020-03-19 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pile', '0003_auto_20200318_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
