# Generated by Django 3.0.4 on 2020-03-20 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pile', '0004_document_hidden'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-id'], 'permissions': [('see_hidden', 'Can see hidden documents')]},
        ),
    ]
