# Generated by Django 3.0.4 on 2020-03-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pile', '0006_auto_20200329_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('REF', 'Referential'), ('STD', 'Standard'), ('FRG', 'Fragment')], default='STD', max_length=3),
        ),
    ]
