# Generated by Django 3.0.4 on 2020-05-21 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pile', '0009_auto_20200402_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='media_type',
            field=models.CharField(choices=[('T', 'Text'), ('A', 'Audio'), ('V', 'Video'), ('+', 'Multiple types'), ('X', 'Other')], default='T', max_length=1),
        ),
    ]
