# Generated by Django 3.0.4 on 2020-06-10 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pile', '0011_document_related'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='related',
            field=models.ManyToManyField(blank=True, related_name='_document_related_+', to='pile.Document'),
        ),
    ]
